server:
  port: 0
spring:
  application:
    name: ms-pagos
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/pagos
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 60

jwt:
  # Clave secreta firmada en Base64 (Mínimo 256 bits / 32 bytes)
  #ClaveSuperSecretaParaPinkPink2026
  secret: "Q2xhdmVTdXBlclNlY3JldGFQYXJhUGlua1BpbmsyMDI2"
  # 3600000 ms = 1 hora de duración para el token
  expiration-ms: 3600000
